[package]
name = "bevy_sprite"
version = "0.14.1"
edition = "2021"
description = "Provides sprite functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
webgl = []
webgpu = []

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.14.1" }
bevy_asset = { path = "../bevy_asset", version = "0.14.1" }
bevy_color = { path = "../bevy_color", version = "0.14.1" }
bevy_core_pipeline = { path = "../bevy_core_pipeline", version = "0.14.1" }
bevy_ecs = { path = "../bevy_ecs", version = "0.14.1" }
bevy_math = { path = "../bevy_math", version = "0.14.1" }
bevy_reflect = { path = "../bevy_reflect", version = "0.14.1", features = [
  "bevy",
] }
bevy_render = { path = "../bevy_render", version = "0.14.1" }
bevy_transform = { path = "../bevy_transform", version = "0.14.1" }
bevy_utils = { path = "../bevy_utils", version = "0.14.1" }
bevy_derive = { path = "../bevy_derive", version = "0.14.1" }

# other
bytemuck = { version = "1", features = ["derive", "must_cast"] }
fixedbitset = "0.5"
guillotiere = "0.6.0"
thiserror = "1.0"
rectangle-pack = "0.4"
bitflags = "2.3"
radsort = "0.1"
nonmax = "0.5"

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--generate-link-to-definition"]
all-features = true
